apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  MONGO_URI: {{ .Values.configmap.MONGO_URI }}
  MONGO_INITDB_DATABASE: {{ .Values.configmap.MONGO_INITDB_DATABASE }}