apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.label.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.label.app }}
    spec:
      containers:
        - name: veg-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: MONGO_URI

