namespace: ritzy-ns

#configmap

configmap:
  MONGO_URI: "mongodb://mongodb:27017/vegetable_order_app"
  MONGO_INITDB_DATABASE: "vegetable_order_app"

#deployment

deployment:
  replicas: 3
  name: veg-container
  label: 
    app: vegetable
image: 
  repository: rithika17/vegetable-order-app
  tag: v1.0.0
port:  3000

#service

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000
  app: vegetable

#mongo statefulset

StatefulSet:
  replicas: 2
  label:
    app: mongodb
  containerName: mongodb-container
image: 
  repository: mongo
  tag: latest
port: 27017
volumes:
  size: 1Gi

#mongo service

mongoService:
  app: mongodb
  port: 27017
  clusterIP: None

#pvc

pvc:
  accessModes: ["ReadWriteOnce"]
  size: 2Gi


#storage class

storageclass:
 provisioner: ebs.csi.aws.com
 parameters:
  type: gp3
 reclaimPolicy: Retain 
 volumeBindingMode: WaitForFirstConsumer
