apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mongodb-statefulset
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.StatefulSet.replicas }}
  serviceName: {{ .Release.Name }}-mongodb-svc
  selector:
    matchLabels:
      app: {{ .Values.StatefulSet.label.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.StatefulSet.label.app }}
    spec:
      containers:
        - name: {{ .Values.StatefulSet.containerName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.port }}
              protocol: TCP
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: MONGO_INITDB_DATABASE
          volumeMounts:
            - mountPath: /data/db 
              name: {{ .Release.Name }}-mongo-data
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-mongo-data
      spec:
        accessModes: {{ .Values.pvc.accessModes }}
        storageClassName: {{ .Release.Name }}-veg-svc
        resources:
          requests:
            storage: {{ .Values.volumes.size }}