apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-veg-svc
  namespace: {{ .Values.namespace }}
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
  type: {{ .Values.storageClass.type }}  # general purpose SSD (gp3, gp2)
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }} 
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}